config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  %w{env help home test}.each { |p| get p => "pages##{p}" }
  get "sign_in" => "sessions#new"

  resources :notes
  resources :positions do
    get :copy, on: :member
    get :select, on: :collection
    get :retire, on: :collection
    get :review, on: :collection
  end
  resources :users

  resource :session, only: [:new, :create, :destroy]
end

app/models/position.rb
class Position < ApplicationRecord
  include Constrainable
  include Pageable

  MAX_OPENING = 25

  belongs_to :user
  has_many :reviews

  before_validation :normalize_attributes, :parse_pgn

  validates :fen, length: { maximum: Fen::MAX }, presence: true, uniqueness: { scope: :user, message: I18n.t("position.errors.dup") }
  validates :opening, length: { maximum: MAX_OPENING }, presence: true
  validates :var, :svar, :ssvar, length: { maximum: MAX_OPENING }, allow_nil: true

  def self.search(matches, params, path, opt={})
    matches = case params[:order]
    when "opening"
      matches.order(:opening, :var, :svar, :ssvar, :updated_at)
    when "created"
      matches.order(created_at: :desc)
    else
      matches.order(updated_at: :desc)
    end
    if sql = cross_constraint(params[:opening], %w{opening var svar ssvar})
      matches = matches.where(sql)
    end
    # matches = opening_author(matches, params) # for now, with only one author, no point
    paginate(matches, params, path, opt)
  end

  def self.select(matches, params, path, opt={})
    matches = opening_author(matches, params)
    if params[:type] == "new"
      pids = Review.where(user_id: params[:user_id]).pluck(:position_id)
      matches = matches.where.not(id: pids).order(:id)
    else
      matches = matches.joins(:reviews).where("reviews.user_id = ?", params[:user_id])
      case params[:type]
      when "day"
        matches = matches.where("reviews.due > ?", Time.now).where("reviews.due <= ?", Time.now + 1.day)
      when "days"
        matches = matches.where("reviews.due > ?", Time.now).where("reviews.due <= ?", Time.now + 3.day)
      when "week"
        matches = matches.where("reviews.due > ?", Time.now).where("reviews.due <= ?", Time.now + 7.day)
      else
        matches = matches.where("reviews.due <= ?", Time.now)
      end
    end
    paginate(matches, params, path, opt)
  end

  def harness
    @harness ||= PgnHarness.new(pgn)
  end

  def game
    @game ||= harness.game
  end

  def title
    [opening, var, svar, ssvar].compact.join(", ")
  end

  private

  def normalize_attributes
    %w(opening var svar ssvar).each do |a|
      if send(a).blank?
        send("#{a}=", nil)
      else
        send(a).squish!
      end
    end
  end

  def parse_pgn
    harness = PgnHarness.new(pgn).check!
    if harness.okay?
      self.pgn = harness.pgn
      self.fen = harness.fen
    else
      errors.add(:pgn, harness.error)
    end
  end

  def self.opening_author(matches, params)
    matches = matches.includes(:user)
    if sql = cross_constraint(params[:opening], %w{opening var svar ssvar})
      matches = matches.where(sql)
    end
    if (user_id = params[:author].to_i) > 0
      matches = matches.where(user_id: user_id)
    end
    matches
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  load_and_authorize_resource except: ["review", "retire"]
  authorize_resource only: ["review", "retire"]

  def index
    @positions = Position.search(@positions, params, positions_path, per_page: 10)
  end

  def select
    per_page = helpers.tests_per_page(params[:per_page])
    params[:user_id] = current_user.id
    @positions = Position.select(@positions, params, select_positions_path, per_page: per_page)
    remember_reviews(@positions)
  end

  def review
    update_test(params[:pid].to_i, params[:quality].to_i)
    @title = reviews_title
    @position = get_next_review
    redirect_to select_positions_path unless @position
  end

  def retire
    forget_reviews
    redirect_to home_path
  end

  def create
    @position.user = current_user
    if @position.save
      redirect_to @position
    else
      failure @position
      render :new
    end
  end

  def update
    if @position.update(resource_params)
      redirect_to @position
    else
      failure @position
      render :edit
    end
  end

  def destroy
    @position.destroy
    redirect_to positions_path
  end

  def copy
    @position = @position.dup
    render :new
  end

  private

  def resource_params
    params.require(:position).permit(:opening, :pgn, :svar, :ssvar, :var)
  end

  def remember_reviews(pager)
    session[:reviews] = pager.matches.pluck(:id)
    session[:rvindex] = 0
    session[:repeats] = []
  end

  def forget_reviews
    session[:reviews] = nil
    session[:rvindex] = nil
    session[:repeats] = nil
  end

  def get_next_review
    pids, rids, i = okay
    return unless i
    position = nil
    if i < pids.length
      position = Position.find_by(id: pids[i])
      session[:rvindex] += 1
    elsif !rids.empty?
      position = Position.find_by(id: rids.first)
      session[:repeats].rotate!
    end
    position
  end

  def update_test(pid, q)
    pids, rids, i = okay
    return unless i
    return unless pids.include?(pid)
    return unless Review::QUALITY.include?(q)
    test = Review.find_or_create_by(position_id: pid, user_id: current_user.id)
    test.step(q)
    test.save!
    if q < 3
      session[:repeats].push(pid) unless rids.include?(pid)
    else
      session[:repeats].delete(pid) if rids.include?(pid)
    end
  end

  def reviews_title
    pids, rids, i = okay
    return I18n.t("review.review") unless i
    if i < pids.length
      "%d of %d Review%s" % [session[:rvindex] + 1, pids.length, pids.length > 1 ? "s" : ""]
    elsif !rids.empty?
      "%d Repeat%s" % [rids.length, rids.length > 1 ? "s" : ""]
    else
      I18n.t("review.review")
    end
  end

  def okay
    vals = []
    return vals unless session[:reviews].is_a?(Array) && !session[:reviews].empty?
    vals.push session[:reviews]
    return vals unless session[:repeats].is_a?(Array)
    vals.push session[:repeats]
    return vals unless session[:rvindex].is_a?(Integer) && session[:rvindex] >= 0
    vals.push session[:rvindex]
    vals
  end
end

app/helpers/position_helper.rb
module PositionHelper
  def position_author_menu(selected)
    opts = Position
      .pluck(:user_id)
      .uniq
      .map{ |id| User.find_by(id: id) }
      .compact
      .sort_by{ |u| u.name }
      .map{ |u| [u.name, u.id] }
    opts.unshift [t("position.author"), ""]
    options_for_select(opts, selected)
  end

  def position_order_menu(selected)
    opts = [
      [t("updated"),          "updated"],
      [t("created"),          "created"],
      [t("position.opening"), "opening"],
    ]
    options_for_select(opts, selected)
  end
end

app/views/positions/_board.js.erb
import { Elm } from "elm_board"

// array of elm apps and index of currently active one
var elm_apps = [];
var elm_active = 0;

// whether keys can be used to update board
// temporarily turned off while review in progress
var keys_active = true;

// setup the app(s), message handling, button controls and keyboard controls
$(function() {
  <% harnesses.each_with_index do |h, i| %>

  // elm app(s)
  elm_apps.push(Elm.Board.init({
    node: $('#elm-app-<%= i %>').get(0),
    flags: {
      bid: <%= i %>,
      fens: [
        <% h.fens.each do |fen| %>
          '<%= fen %>',
        <% end %>
      ],
      orientation: '<%= h.player %>',
      index: <%= h.index %>,
    },
  }));
  <% end %>

  // foreach app
  $.each(elm_apps, function(i, app) {
    // handle a state message (in response to a button click or keypress) coming out of an app
    app.ports.state.subscribe(function(state) {
      // update buttons
      $('#btn-' + state.bid + '-s').prop('disabled', state.start);
      $('#btn-' + state.bid + '-r').prop('disabled', state.reset);
      $('#btn-' + state.bid + '-p').prop('disabled', state.start);
      $('#btn-' + state.bid + '-n').prop('disabled', state.end);

      // update moves
      $('.em-' + state.bid).removeClass('current-move');
      $('#em-' + state.bid + '-' + state.index).addClass('current-move');

      // make this app the active one (for keypresses)
      elm_active = state.bid;
    });

    // handle error messages
    app.ports.error.subscribe(function(msg) {
      console.log(msg);
    });
  });

  // when button clicked, send message to app
  $('.elm-btn').on('click', function(e) {
    var m = $(e.target).attr('id').match(/-(\d+)-([nprs])/);
    var bid = parseInt(m[1]);
    var btn = m[2];
    elm_apps[bid].ports.updateIndex.send(btn);
  });

  // when move clicked, send message to app
  $('.elm-move').on('click', function(e) {
    var m = $(e.target).attr('id').match(/em-(\d+)-(\d+)/);
    var bid = parseInt(m[1]);
    var ind = m[2];
    elm_apps[bid].ports.updateIndex.send(ind);
  });

  // when certain keys pressed, send message to app
  $(window).keydown(function(e) {
    if (keys_active) {
      var app = elm_apps[elm_active];
      switch (e.keyCode) {
        case 39: // right arrow
        case 76: // 'l' for right
        case 78: // 'n' for next
          app.ports.updateIndex.send('n');
          break;
        case 37: // left arrow
        case 72: // 'h' for left
        case 80: // 'p' for previous
          app.ports.updateIndex.send('p');
          break;
        case 75: // 'k' for up
        case 82: // 'r' for restart
          app.ports.updateIndex.send('r');
          break;
        case 83: // 's' for start
        case 74: // 'j' for down
          app.ports.updateIndex.send('s');
          break;
      }
    }
  });

  // fire a reset at each app so that each responds with a state
  // update which, when handled (see above), will sort the buttons
  $.each(elm_apps, function(i, app) {
    app.ports.updateIndex.send('r');
  });
});

app/views/positions/_form.html.haml
:ruby
  inputs = [
    [:opening, t("position.opening"), :text, maxlength: Position::MAX_OPENING],
    [:var,     t("position.var"),     :text, maxlength: Position::MAX_OPENING],
    [:svar,    t("position.svar"),    :text, maxlength: Position::MAX_OPENING],
    [:ssvar,   t("position.ssvar"),   :text, maxlength: Position::MAX_OPENING],
    [:pgn,     t("position.pgn"),     :area],
  ]
= render "utils/crud/form", object: position, index: positions_path, inputs: inputs, title: title, center: center(xl: 8, lg: 10)

app/views/positions/_results.html.haml
- positions.matches.each do |position|
  %tr
    %td.text-center= link_to position.id, position, "data-turbo" => "false"
    %td= position.title
    %td= position.user.name
= render "utils/pagination/links", pager: positions, columns: 3

app/views/positions/_review.js.erb
$(function() {
  $('#answer').hide();
  $('#moves').hide();
  $('#buttons').hide();
  $('button.report').hide();
  keys_active = false;

  $('#show').click(function() {
    $('#show').hide();
    $('#modesty').hide();
    $('#answer').show();
    $('#moves').show();
    $('#buttons').show();
    $('button.report').show();
    elm_apps[elm_active].ports.updateIndex.send('n');
    keys_active = true;
  });

  $('button.report').click(function() {
    var quality = $(this).attr('data-quality');
    window.location.href = '/positions/review?pid=' + <%= pid %> + '&quality=' + quality;
  });
});

app/views/positions/_selections.html.haml
- positions.matches.each do |position|
  %tr
    %td= position.title
    %td= position.user.name
= render "utils/pagination/links", pager: positions, columns: 2

app/views/positions/edit.html.haml
- set_meta_tags title: t("position.edit")
= render "form", position: @position, title: t("position.edit")

app/views/positions/index.html.haml
:ruby
  set_meta_tags title: t("position.title")
  lo = Layout.new(
    sm: [[3,3]],
  ).to_a
  inputs = [
    [:opening, t("position.opening"), :text,   lo[0], autofocus: true],
    [:order,   t("order"),            :select, lo[1], menu: position_order_menu(params[:order])],
  ]

%section
  .header{class: "#{can?(:create, Position) ? '' : 'text-center'}"}
    %h3.d-inline= t("position.title")
    - if can?(:create, Position)
      .float-end.mt-1= link_to t("position.new"), new_position_path, class: "btn btn-primary btn-sm"
  .body{"data-turbo" => "true"}
    = render "utils/search/form", index: positions_path, inputs: inputs
    .row
      %div{class: center(xl: 6, lg: 8, md: 10, sm: 12)}
        = turbo_frame_tag :results, "data-turbo-action" => "advance" do
          %table.mt-4{class: "table table-bordered table-sm"}
            %thead
              %tr
                %th.text-center= "#"
                %th= t("position.opening")
                %th= t("position.author")
            %tbody
              = render "results", positions: @positions

app/views/positions/new.html.haml
- set_meta_tags title: t("position.new")
= render "form", position: @position, title: t("position.new")

app/views/positions/review.html.haml
- set_meta_tags title: t("review.review")

- content_for :javascript do
  = render partial: "board", formats: :js, locals: { harnesses: [@position.harness] }
  = render partial: "review", formats: :js, locals: { pid: @position.id }

%section
  .header
    %h3= @title
  .body
    %div{class: center(xl: 4, lg: 6, md: 8, sm: 10)}
      %div{id: "elm-app-0"}
      .text-center#buttons
        %button.elm-btn{id: "btn-0-s"}= t("position.btn.start")
        %button.elm-btn{id: "btn-0-r"}= t("position.btn.reset")
        %button.elm-btn{id: "btn-0-p"}= t("position.btn.prev")
        %button.elm-btn{id: "btn-0-n"}= t("position.btn.next")
    .moves#moves= @position.harness.html
    .text-center.mt-3
      %button.btn.btn-sm.btn-success#show= t("review.reveal")
      - (0..5).each do |q|
        %button.btn.btn-sm.report{class: "btn-#{t("review.btn.class")[q]}", "data-quality" => q}
          = t("review.btn.text")[q]
  .footer
    = link_to t("review.retire"), retire_positions_path, class: "btn btn-sm btn-danger"
    - if can?(:edit, @position)
      = link_to t("edit"), edit_position_path(@position), class: "btn btn-primary btn-sm", target: "edit"

app/views/positions/select.html.haml
:ruby
  set_meta_tags title: t("review.title")
  lo = Layout.new(
    md: [[2,2,2,2]],
    xs: [[3,3,3,3]],
  ).to_a
  inputs = [
    [:opening,  t("position.opening"), :text,   lo[0]],
    [:author,   t("position.author"),  :select, lo[1], menu: position_author_menu(params[:author])],
    [:type,     t("review.type"),      :select, lo[2], menu: test_order_menu(params[:type])],
    [:per_page, t("per_page"),         :select, lo[3], menu: tests_per_page_menu(params[:per_page])],
  ]

%section
  .header{class: "#{can?(:create, Position) ? '' : 'text-center'}"}
    %h3.d-inline= t("review.title")
  .body{"data-turbo" => "true"}
    = render "utils/search/form", index: select_positions_path, inputs: inputs
    .row
      %div{class: center(xl: 6, lg: 8, md: 10, sm: 12)}
        = turbo_frame_tag :results, "data-turbo-action" => "advance" do
          %table.mt-4{class: "table table-bordered table-sm"}
            %thead
              %tr
                %th= t("position.opening")
                %th= t("position.author")
            %tbody#results
              = render "selections", positions: @positions
  .footer
    = link_to t("review.review"), review_positions_path, class: "btn btn-success btn-sm"

app/views/positions/show.html.haml
- set_meta_tags title: @position.title

- content_for :javascript do
  = render partial: "board", formats: :js, locals: { harnesses: [@position.harness] }

%section
  .header
    %h3.d-inline= @position.title
  .body
    .div{class: center(xl: 4, lg: 6, md: 8, sm: 10)}
      .div{id: "elm-app-0"}
      .text-center
        %button.elm-btn{id: "btn-0-s"}= t("position.btn.start")
        %button.elm-btn{id: "btn-0-r"}= t("position.btn.reset")
        %button.elm-btn{id: "btn-0-p"}= t("position.btn.prev")
        %button.elm-btn{id: "btn-0-n"}= t("position.btn.next")
    .moves= @position.harness.html

  .footer
    - if can?(:edit, @position)
      = link_to t("edit"), edit_position_path(@position), class: "btn btn-primary btn-sm"
      = link_to t("copy"), copy_position_path(@position), class: "btn btn-primary btn-sm"
    %span{"data-controller" => "clipboard"}
      %input.d-none{"data-clipboard-target" => "fen", type: "text", value: @position.fen, readonly: true}
      %button.btn.btn-success.btn-sm{"data-action" => "clipboard#copy"}= t("position.fen")
    = link_to t("position.title"), positions_path, class: "btn btn-success btn-sm"