config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  %w{env help home test}.each { |p| get p => "pages##{p}" }
  get "sign_in" => "sessions#new"

  resources :notes
  resources :positions do
    get :copy, on: :member
    get :select, on: :collection
    get :retire, on: :collection
    get :review, on: :collection
  end
  resources :users

  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  MAX_EMAIL = 50
  MAX_NAME = 30
  MIN_PASSWORD = 8

  has_secure_password

  before_validation :normalize_attributes

  validates :email, format: { with: /\A\S+@\S+\z/ }, length: { maximum: MAX_EMAIL }, uniqueness: { case_sensitive: false }
  validates :name, length: { maximum: MAX_NAME }, presence: true, uniqueness: true
  validates :password, length: { minimum: MIN_PASSWORD }, allow_nil: true

  default_scope { order(:name) }

  def guest?
    false
  end

  private

  def normalize_attributes
    email&.squish!&.downcase
    name&.squish!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def create
    if @user.save
      redirect_to @user
    else
      failure @user
      render :new
    end
  end

  def update
    if @user.update(resource_params)
      redirect_to @user
    else
      failure @user
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def resource_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def admin(user)
    t("symbol.#{user.admin? ? 'tick' : 'cross'}")
  end
end

app/views/users/_form.html.haml
:ruby
  inputs = [
    [:name,     t("user.name"),     :text,     maxlength: User::MAX_NAME],
    [:email,    t("user.email"),    :text,     maxlength: User::MAX_EMAIL],
    [:password, t("user.password"), :password],
  ]
= render "utils/crud/form", object: user, index: users_path, inputs: inputs, title: title, center: center(xl: 4, lg: 6, md: 8, sm: 10)

app/views/users/edit.html.haml
- set_meta_tags title: t("user.edit")
= render "form", user: @user, title: t("user.edit")

app/views/users/index.html.haml
- set_meta_tags title: t("user.users")

%section
  .header{class: "#{can?(:create, User) ? '' : 'text-center'}"}
    %h3.d-inline= t("user.users")
    - if can?(:create, User)
      .float-end.mt-1= link_to t("user.new"), new_user_path, class: "btn btn-primary btn-sm"
  .body
    %table{class: "table table-bordered table-sm mt-3"}
      %thead
        %tr
          %th= t("user.email")
          %th= t("user.name")
          %th.text-center= t("user.admin")
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.email, user
            %td= user.name
            %td.text-center= t("symbol.tick") if user.admin?

app/views/users/new.html.haml
- set_meta_tags title: t("user.new")
= render "form", user: @user, title: t("user.new")

app/views/users/show.html.haml
- set_meta_tags title: @user.name

.row
  %div{class: center(xl: 4, lg: 6, md:8, sm: 10)}
    %section
      .header.text-center
        %h3.d-inline= @user.name
      .body
        %table{class: "table table-bordered mt-3"}
          %tbody
            %tr
              %th= t("user.email")
              %td= @user.email
            %tr
              %th= t("user.admin")
              %td= admin(@user)
      .footer
        - if can?(:edit, @user)
          = link_to t("edit"), edit_user_path(@user), class: "btn btn-primary btn-sm"
        = link_to t("user.users"), users_path, class: "btn btn-success btn-sm"