config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  %w{env help home test}.each { |p| get p => "pages##{p}" }
  get "sign_in" => "sessions#new"

  resources :notes
  resources :positions do
    get :copy, on: :member
    get :select, on: :collection
    get :retire, on: :collection
    get :review, on: :collection
  end
  resources :users

  resource :session, only: [:new, :create, :destroy]
end

app/models/layout.rb
class Layout
  BP = %w/xs sm md lg xl xx xxl/.map(&:to_sym)

  def initialize(args)
    raise I18n.t("layout.error.input") unless args.is_a?(Hash)
    @bps = BP.each_with_object({}){ |bp, h| h[bp] = args[bp] if args[bp].is_a?(Array) }
    @bps[:xxl] = @bps.delete(:xx) if @bps.has_key?(:xx)
    check!
    @col = @bps.map{ |bp, arrays_or_numbers| @rmg = 0; transform(arrays_or_numbers, bp) }
  end

  def to_a
    (0...@number).map{ |i| @col.map{ |col| col[i] }.join(" ") }
  end

  private

  def check!
    raise I18n.t("layout.error.keys") if @bps.empty?
    @number = nil
    @bps.each_pair do |bp, row_or_cols|
      if row_or_cols.map{|w| w.is_a?(Integer)}.all?
        row = row_or_cols
        raise I18n.t("layout.error.empty") if row.empty?
        raise I18n.t("layout.error.width") unless row.map{|w| w > 0 && w <= 12}.all?
        raise I18n.t("layout.error.total") if row.sum > 12
        if @number
          raise I18n.t("layout.error.number") unless @number == row.length
        else
          @number = row.length
        end
      else
        cols = row_or_cols
        cols.each do |row|
          raise I18n.t("layout.error.row") unless row.is_a?(Array) && !row.empty?
          raise I18n.t("layout.error.width") unless row.map{|w| w.is_a?(Integer) && w > 0 && w <= 12}.all?
          raise I18n.t("layout.error.total") if row.sum > 12
        end
        if @number
          raise I18n.t("layout.error.number") unless @number == cols.map(&:length).sum
        else
          @number = cols.map(&:length).sum
        end
      end
    end
  end

  def transform(arrays_or_numbers, bp)
    if arrays_or_numbers.first.is_a?(Integer)
      transform_numbers(arrays_or_numbers, bp)
    else
      transform_arrays(arrays_or_numbers, bp)
    end
  end

  def transform_numbers(numbers, bp)
    numbers.each_with_index.map do |n, i|
      col = bp == :xs ? "col-#{n}" : "col-#{bp}-#{n}"
      if i == 0
        lmg = ((12 - numbers.sum) / 2.0).ceil
        m = lmg
        m += @rmg unless lmg + n > @rmg
        col += bp == :xs ? " offset-#{m}" : " offset-#{bp}-#{m}"
        @rmg = 12 - n - lmg
      else
        col += bp == :xs ? " offset-0" : " offset-#{bp}-0"
        @rmg -= n
      end
      col
    end
  end

  def transform_arrays(arrays, bp)
    arrays.map{ |numbers| transform_numbers(numbers, bp) }.flatten
  end
end

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  .flash.alert.alert-dismissable{class: type == "alert" ? "rails-alert" : type}
    %button.close{"type" => "button", "data-bs-dismiss" => "alert"}= t("symbol.cross")
    = message

app/views/layouts/_head.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
%meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
= display_meta_tags site: t("title")
= csrf_meta_tags
= csp_meta_tag
= javascript_importmap_tags
- if content_for? :javascript
  %script{type: "module", nonce: content_security_policy_nonce}
    = yield :javascript
= stylesheet_link_tag "application", media: "all", "data-turbo-track" => "reload"

app/views/layouts/_nav.html.haml
%nav
  .container-fluid
    = link_to root_path, class: "navbar-brand" do
      = image_tag "logo.png", width: 30, height: 30, alt: "logo"
    %button{type: "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#navbar"}
      %span
    #navbar.collapse.navbar-collapse
      %ul.me-auto
        - if can?(:select, Position)
          %li= link_to t("review.title"), select_positions_path
        - if can?(:read, Position)
          %li= link_to t("position.title"), positions_path
        - if current_user.admin?
          %li.dropdown
            = link_to t("user.admin"), "#", class: "dropdown-toggle", "data-bs-toggle" => "dropdown", role: "button"
            %ul.dropdown-menu
              %li= link_to t("user.users"), users_path
              %li= link_to t("pages.test.title"), test_path
              %li= link_to t("pages.env.title"), env_path
      %ul.ms-auto
        - unless controller_name == "sessions"
          - if current_user.guest?
            %li= link_to t("session.sign_in"), new_session_path
          - else
            %li{"data-turbo" => "true"}= link_to t("session.sign_out"), session_path, "data-turbo-method" => "delete"

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    = render "layouts/head"
  %body
    .container.mt-4.mb-4
      = render "layouts/nav"
      = render "layouts/flash"
      = yield